name: Betanygonz deploy
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.2
      - name: Install packages
        run: yarn install
      - name: bundle
        run: yarn run start
